blogdjango/myblog/blog/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^(?P<pk>\d+)/$', views.EntryDetail.as_view(), name='entry_detail'),
]

blogdjango/myblog/myblog/urls.py
from django.conf.urls import include, url
from django.contrib import admin

import blog.urls
from . import views

urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^', include(blog.urls)),
    url(r'^admin/', include(admin.site.urls)),
]

blogdjango/myblog/blog/models.py
from django.db import models
from django.core.urlresolvers import reverse
# Create your models here.

class Entry(models.Model):
    title = models.CharField(max_length=500)
    author = models.ForeignKey('auth.User')
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    modified_at = models.DateTimeField(auto_now=True, editable=False)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('entry_detail', kwargs={'pk': self.pk})

    class Meta:
        verbose_name_plural = "entries"

blogdjango/myblog/blog/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import DetailView
from .models import Entry


class EntryDetail(DetailView):
    model = Entry

blogdjango/myblog/myblog/views.py
from django.views.generic import ListView

from blog.models import Entry

class HomeView(ListView):

    template_name = 'index.html'
    queryset = Entry.objects.order_by('-created_at')

blogdjango/myblog/templates/_entry.html
<article>

    <h2><a href="{{ entry.get_absolute_url }}">{{ entry.title }}</a></h2>

    <p class="subheader">
        <time>{{ entry.modified_at|date }}</time>
    </p>

    <p></p>

    {{ entry.body|linebreaks }}

</article>

blogdjango/myblog/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title>My Blog</title>
    <link rel="stylesheet" href="{% static "css/foundation.css" %}">
</head>
<body>
    <section class="row">
        <header class="large-12 columns">
            <h1>Welcome to My Blog</h1>
            <hr>
        </header>
    </section>

    <section class="row">

        <div class="large-8 columns">
            {% block content %}{% endblock %}
        </div>

        <div class="large-4 columns">
            <h3>About Me</h3>
            <p>I am a Python developer and I like Django.</p>
        </div>

    </section>

</body>
</html>

blogdjango/myblog/templates/blog/entry_detail.html
{% extends "base.html" %}

{% block content %}
    {% include "_entry.html" with entry=entry only %}
{% endblock %}

blogdjango/myblog/templates/index.html
{% extends "base.html" %}

{% block content %}
    {% for entry in entry_list %}
            {% include "_entry.html" with entry=entry only %}
        {% empty %}
        <p>No blog entries yet.</p>
    {% endfor %}
{% endblock content %}